name: music_player
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  windows_taskbar: ^1.1.0+1
  bitsdojo_window: ^0.1.5
  path_provider: ^2.0.11
  audioplayers: ^1.1.1
  window_manager: ^0.2.7
  cupertino_icons: ^1.0.2
  flutter_media_metadata: ^1.0.0+1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  url_launcher: ^6.1.6
  file_picker: ^5.2.1
  keyboard_event: ^0.3.2
  desktop_window: ^0.4.0
  provider: ^6.0.4

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf

